package com.heyoung.domain.outbox.enums;

public enum DeliveryErrorType {
    NONE_RESPONSE, NETWORK, TIMEOUT, HTTP_4XX, HTTP_5XX, OTHER_ERROR,
    INVALID_SIGNATURE, INVALID_PAYLOAD, RATE_LIMITED, DESTINATION_UNAVAILABLE, UNKNOWN
}
